import { BettingGridType } from "@/types/BettingTypes";

export const BettingGridItems : BettingGridType[] = [
    { betNumber: 1, query: "row-1 column-1 odd", color: "red" },
    { betNumber: 2, query: "row-1 column-2 even", color: "black" },
    { betNumber: 3, query: "row-1 column-3 odd", color: "red" },
    { betNumber: 4, query: "row-2 column-1 even", color: "black" },
    { betNumber: 5, query: "row-2 column-2 odd", color: "red" },
    { betNumber: 6, query: "row-2 column-3 even", color: "black" },
    { betNumber: 7, query: "row-3 column-1 odd", color: "red" },
    { betNumber: 8, query: "row-3 column-2 even", color: "black" },
    { betNumber: 9, query: "row-3 column-3 odd", color: "red" },
    { betNumber: 10, query: "row-4 column-1 even", color: "black" },
    { betNumber: 11, query: "row-4 column-2 odd", color: "black" },
    { betNumber: 12, query: "row-4 column-3 even", color: "red" },
    { betNumber: 13, query: "row-5 column-1 odd", color: "black" },
    { betNumber: 14, query: "row-5 column-2 even", color: "red" },
    { betNumber: 15, query: "row-5 column-3 odd", color: "black" },
    { betNumber: 16, query: "row-6 column-1 even", color: "red" },
    { betNumber: 17, query: "row-6 column-2 odd", color: "black" },
    { betNumber: 18, query: "row-6 column-3 even", color: "red" },
    { betNumber: 19, query: "row-7 column-1 odd", color: "red" },
    { betNumber: 20, query: "row-7 column-2 even", color: "black" },
    { betNumber: 21, query: "row-7 column-3 odd", color: "red" },
    { betNumber: 22, query: "row-8 column-1 even", color: "black" },
    { betNumber: 23, query: "row-8 column-2 odd", color: "red" },
    { betNumber: 24, query: "row-8 column-3 even", color: "black" },
    { betNumber: 25, query: "row-9 column-1 odd", color: "red" },
    { betNumber: 26, query: "row-9 column-2 even", color: "black" },
    { betNumber: 27, query: "row-9 column-3 odd", color: "red" },
    { betNumber: 28, query: "row-10 column-1 even", color: "black" },
    { betNumber: 29, query: "row-10 column-2 odd", color: "black" },
    { betNumber: 30, query: "row-10 column-3 even", color: "red" },
    { betNumber: 31, query: "row-11 column-1 odd", color: "black" },
    { betNumber: 32, query: "row-11 column-2 even", color: "red" },
    { betNumber: 33, query: "row-11 column-3 odd", color: "black" },
    { betNumber: 34, query: "row-12 column-1 even", color: "red" },
    { betNumber: 35, query: "row-12 column-2 odd", color: "black" },
    { betNumber: 36, query: "row-12 column-3 even", color: "red" },
];